/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import DAO.DAOException;
import DAO.DAOManager;
import DAOMySQL.MySQLDAOManager;
import Modelo.cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesús Moisés
 */
public class JDAñadirCliente extends javax.swing.JDialog {
     //Creamos un objeto de tipo interface IClienteDAO
    private DAOManager manager = null;
    
    //Campos para alamcenar los datos del formulario
    private String nombreCliente;
    private String apellidoPaterno;
    private String apellidoMaterno;
    private String domicilio;
    private String celular;
    private String correo;
    /**
     * Creates new form JDAñadirCliente
     */
    public JDAñadirCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.manager = new MySQLDAOManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        txtMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        txtPaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelImage6 = new org.edisoncor.gui.panel.PanelImage();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelImage7 = new org.edisoncor.gui.panel.PanelImage();
        txtCelular = new javax.swing.JTextField();
        panelImage8 = new org.edisoncor.gui.panel.PanelImage();
        txtDomicilio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAñadirCli = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 214, 71));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 690, 10));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        panelImage4.setBackground(new java.awt.Color(255, 255, 255));
        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setBorder(null);
        panelImage4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, 40));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));

        panelImage5.setBackground(new java.awt.Color(255, 255, 255));
        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaterno.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtMaterno.setForeground(new java.awt.Color(153, 153, 153));
        txtMaterno.setBorder(null);
        panelImage5.add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, 40));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("Apellido Paterno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        panelImage3.setBackground(new java.awt.Color(255, 255, 255));
        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPaterno.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtPaterno.setForeground(new java.awt.Color(153, 153, 153));
        txtPaterno.setBorder(null);
        panelImage3.add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 180, 40));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("Domicilio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        panelImage6.setBackground(new java.awt.Color(255, 255, 255));
        panelImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setBorder(null);
        panelImage6.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 180, 40));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Teléfono Celular:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        panelImage7.setBackground(new java.awt.Color(255, 255, 255));
        panelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCelular.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(153, 153, 153));
        txtCelular.setBorder(null);
        panelImage7.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 40));

        panelImage8.setBackground(new java.awt.Color(255, 255, 255));
        panelImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDomicilio.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtDomicilio.setForeground(new java.awt.Color(153, 153, 153));
        txtDomicilio.setBorder(null);
        panelImage8.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 180, 40));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("E-Mail:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        btnAñadirCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgRegistrar/nuevoCliente.png"))); // NOI18N
        btnAñadirCli.setBorder(null);
        btnAñadirCli.setBorderPainted(false);
        btnAñadirCli.setContentAreaFilled(false);
        btnAñadirCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadirCli.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgRegistrar/nuevoCliente (1).png"))); // NOI18N
        btnAñadirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirCliActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 60, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/close door.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/open door.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 30, 50));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgRegistrar/imgAñadirCli.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 60));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("Salir");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 40, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("Añadir");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirCliActionPerformed
        /*
        si se Hace clic en este bóton, se hará el registro en laBD si todo está 
        Correcto
        */
        if(validar()){
            //llamamos el constructor para crear un Objeto de tipo Cliente
            cliente miCliente = new cliente(nombreCliente, apellidoPaterno, apellidoMaterno, domicilio, celular, correo);

                try{
                    manager.getClienteDAO().insertar(miCliente);
                    JOptionPane.showMessageDialog(null, "<html><h2>El Cliente se ha Registardo Correctamente</h2></html>");
                    limpiarFormulario();
                }catch(DAOException ex){
                    mensajeError(ex);
                }// fin del catch
            this.dispose();
            }// fin del if validar   
    }//GEN-LAST:event_btnAñadirCliActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Cerramos el JDAñadirCliente
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAñadirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAñadirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAñadirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAñadirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAñadirCliente dialog = new JDAñadirCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirCli;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelImage6;
    private org.edisoncor.gui.panel.PanelImage panelImage7;
    private org.edisoncor.gui.panel.PanelImage panelImage8;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para validar que todos los campos de texto esten llenos
     * @return true si está todo correcto
     * @return false si faltan datos
     */
    private boolean validar() {
        boolean validacion = false;
        
        nombreCliente= txtNombre.getText().trim();
        apellidoPaterno = txtPaterno.getText().trim();
        apellidoMaterno = txtMaterno.getText().trim();
        domicilio = txtDomicilio.getText().trim();
        celular = txtCelular.getText().trim();
        correo = txtCorreo.getText().trim();
        
        if(nombreCliente.equals("")){
            JOptionPane.showMessageDialog(null, "Ingresa un nombre de Usuario");
            txtNombre.requestFocusInWindow();
            return validacion;
        }// fin del if nombreUsuario

        if(apellidoPaterno.equals("")){
            JOptionPane.showMessageDialog(null, "Ingresa un Apellido Paterno");
            txtPaterno.requestFocusInWindow();
            return validacion;
        }// fin del if apellidPaterno
        
        if(apellidoMaterno.equals("")){
            JOptionPane.showMessageDialog(null, "Ingresa un Apellido Materno");
            txtMaterno.requestFocusInWindow();
            return validacion;
        }// fin del if apellidoMaterno
        
        if(domicilio.equals("")){
            JOptionPane.showMessageDialog(null, "Ingresa un Domicilio");
            txtDomicilio.requestFocusInWindow();
            return validacion;
        }// fin del if domicilio
        
        if(celular.equals("")){
            JOptionPane.showMessageDialog(null, "Ingresa un Número de Celular");
            txtCelular.requestFocusInWindow();
            return validacion;
        }// fin del if celular
        
        if(correo.equals("")){
            JOptionPane.showMessageDialog(null, "Ingresa un correo");
            txtCorreo.requestFocusInWindow();
            return validacion;
        }// fin del if correo
        
        return true;
    }// fin del método validar

    /**
     * Método para limpiar las cajas de texto y poner el cursor en el campo de
     * nombre
     */
    private void limpiarFormulario() {
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtDomicilio.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
        txtNombre.requestFocusInWindow();
    }// fin del método limpiarFormulario

    /**
     *  Metodo para Mandar Mensaje de Error
     * @param ex 
     */
    private void mensajeError(DAOException ex) {
        //Si getMessage existe obtenemos su valor
        String mensajeError;

        try{
            mensajeError = "Mensaje: " + ex.getCause().getMessage();
        }catch(NullPointerException error){
            mensajeError = "";
        }// fin del catch

        JOptionPane.showMessageDialog(null, ex.getMessage()+"\n"+mensajeError,"ERROR",
                JOptionPane.ERROR_MESSAGE);
    }// fin del método mensajeError
   
}// fin de la clase JDAñadirCliente
