/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import DAO.DAOException;
import DAO.DAOManager;
import DAOMySQL.MySQLDAOManager;
import Modelo.cliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Jesús Moisés
 */
public class JDGesEditarCli extends javax.swing.JDialog {

    //Creamos un objeto de tipo interface IClienteDAO
    private DAOManager manager = null;
  
    //Modelo para nuestra tablaClientes
    private ClientesTableModel model;
    
    //Propiedades para  modificar el width de nuestra tabla tblPeliculas
    TableColumnModel columnModel = null;
    
    int cli_ID;
    String nombre;
    String paterno;
    String materno;
    String domicilio;
    String celular;
    String correo;
    int fila;
    /**
     * Creates new form JDGesEditarCli
     */
    public JDGesEditarCli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Obtenemos todos los métodos de la clase MySQLClienteDAO
        this.manager = new MySQLDAOManager();
        try {
            //llamamos el método inicializarListaClientes
            inicializarListaClientes();
        } catch (DAOException ex) {
            Logger.getLogger(JDGesEditarCli.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Mandamos llamar el método dehabilitar
        deshabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelImage7 = new org.edisoncor.gui.panel.PanelImage();
        txtCelular = new javax.swing.JTextField();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        txtMaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelImage6 = new org.edisoncor.gui.panel.PanelImage();
        txtCorreo = new javax.swing.JTextField();
        panelImage8 = new org.edisoncor.gui.panel.PanelImage();
        txtDomicilio = new javax.swing.JTextField();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        txtPaterno = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelImage9 = new org.edisoncor.gui.panel.PanelImage();
        txtNombre = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 214, 71));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 710, 10));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 130, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Teléfono Celular:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        panelImage7.setBackground(new java.awt.Color(255, 255, 255));
        panelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCelular.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtCelular.setBorder(null);
        panelImage7.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 180, 40));

        panelImage5.setBackground(new java.awt.Color(255, 255, 255));
        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaterno.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtMaterno.setBorder(null);
        panelImage5.add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 180, 40));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("Apellido Paterno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("Domicilio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("E-Mail:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        panelImage6.setBackground(new java.awt.Color(255, 255, 255));
        panelImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtCorreo.setBorder(null);
        panelImage6.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 180, 40));

        panelImage8.setBackground(new java.awt.Color(255, 255, 255));
        panelImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDomicilio.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtDomicilio.setBorder(null);
        panelImage8.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 180, 40));

        panelImage3.setBackground(new java.awt.Color(255, 255, 255));
        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPaterno.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtPaterno.setBorder(null);
        panelImage3.add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 180, 40));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/añadirPeli.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/añadirPeli(1).png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 60, 50));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("Actualizar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/close door.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/open door.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 30, 50));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("Salir");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 40, -1));

        panelImage9.setBackground(new java.awt.Color(255, 255, 255));
        panelImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/campotxt2.png"))); // NOI18N
        panelImage9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtNombre.setBorder(null);
        panelImage9.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jPanel1.add(panelImage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 180, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel10.setText("Editar Cliente");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 640, 130));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        if(validar()){
            cli_ID = (int) tblClientes.getValueAt(fila, 0);
            //llamamos el constructor para crear un objeto de tipo cliente
            cliente miCliente = new cliente(nombre, paterno, materno, domicilio, celular, correo, cli_ID);
            
            try {
                manager.getClienteDAO().modificar(miCliente);
                JOptionPane.showMessageDialog(null, "Los cambios han sido guardados exitosamente");
                //llamamos el método limpiarFormulario 
                limpiarFormulario();
                //llamamos el método deshabilitar
                deshabilitar();
                //llamamos el método inicializarListaClientes
                inicializarListaClientes();
            } catch (DAOException ex) {
               mensajeError(ex);
            }// fin del catch
        }// fin del if validar
      
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Cerramos el JDAñadirCliente
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tblClientes.getSelectedRow() > -1){
            llenarCampos();
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona un cliente a Editar o Eliminar");
        }// fin del else
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         //Solo se puede eliminar si el idAutor es = -1
       
        cli_ID = (int) tblClientes.getValueAt(fila, 0);
            
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Deseas eliminar el cliente con el id = "
                +cli_ID+"?","Confirmar",0);
            
        //si la respuesta es igual a 0 entonces procedemos a intentar eliminar
        if(respuesta == 0){
            try{
                manager.getClienteDAO().eliminar(cli_ID);   
                //si no ocurre una excepción 
                JOptionPane.showMessageDialog(null, "El autor ha sido eliminado");
               //llamamos el método limpiarFormulario 
                limpiarFormulario();
                //llamamos el método deshabilitar
                deshabilitar();
                //llamamos el método inicializarListaCliente
                inicializarListaClientes();
            }catch(DAOException ex){
                imprimirMensajeDeErrorDAO(ex);
            }//fin del catch
        }// fin del if respuesta
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDGesEditarCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDGesEditarCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDGesEditarCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDGesEditarCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDGesEditarCli dialog = new JDGesEditarCli(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelImage6;
    private org.edisoncor.gui.panel.PanelImage panelImage7;
    private org.edisoncor.gui.panel.PanelImage panelImage8;
    private org.edisoncor.gui.panel.PanelImage panelImage9;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para dehabilitar los campos de los datos del cliente y los botones
     * Actualizar y Eliminar
     */
    private void deshabilitar() {
        txtNombre.setEnabled(false);
        txtPaterno.setEnabled(false);
        txtMaterno.setEnabled(false);
        txtDomicilio.setEnabled(false);
        txtCelular.setEnabled(false);
        txtCorreo.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }// fin del método deshabilitar

    /**
     * Imprime un mensaje de error personalizado para aquellos errores que son
     * producidos por el acceso a la BD
     * @param  objeto de tipo DAOException
     */
    private void imprimirMensajeDeErrorDAO(DAOException ex) {
         //Si getMessage existe obtenemos su valor
        String mensajeError;

        try{
            mensajeError = "Mensaje: " + ex.getCause().getMessage();
        }catch(NullPointerException error){
            mensajeError = "ID Cliente no Encontrado";
        }// fin del catch

        JOptionPane.showMessageDialog(null, ex.getMessage()+"\n"+mensajeError,"ERROR",
                JOptionPane.ERROR_MESSAGE);
    }// fin del método imprimirMensajeDeErrorDAO

    /**
    * Método para colocar los titulos a nuestra tabla
    */
    private void inicializarListaClientes() throws DAOException {
        
        model = new ClientesTableModel(manager.getClienteDAO());
            
        //Asignamos el modelo y ponemos los titulos a ver en nuestra tabla
        tblClientes.setModel(model);
        model.updateModel();
        model.fireTableDataChanged();
    }// fin del método inicializarListaAutores

    /**
     * Método para llenar todos los campos con los datos obtenidos de nuestra tabla
     */
    private void llenarCampos() {
        //Obtenemos la fila seleccionada
        fila = tblClientes.getSelectedRow();
        
        //Obtenemos los datos de la fila 
        nombre = (String) tblClientes.getValueAt(fila, 1);
        paterno = (String) tblClientes.getValueAt(fila, 2);
        materno = (String) tblClientes.getValueAt(fila, 3);
        domicilio = (String) tblClientes.getValueAt(fila, 4);
        celular = (String) tblClientes.getValueAt(fila, 5);
        correo = (String) tblClientes.getValueAt(fila, 6);
        
        //Colocamos los datos obtenidos de la fila seleccionada en los campos
        txtNombre.setText(nombre);
        txtPaterno.setText(paterno);
        txtMaterno.setText(materno);
        txtDomicilio.setText(domicilio);
        txtCelular.setText(celular);
        txtCorreo.setText(correo);
        
        //llamamos el método habilitar
        habilitar();
                
    }// fin del método llenar campos

    /**
     * Método para habilitar los campos de texto y los botones Actualizar y 
     * Eliminar
     */
    private void habilitar() {
        txtNombre.setEnabled(true);
        txtPaterno.setEnabled(true);
        txtMaterno.setEnabled(true);
        txtDomicilio.setEnabled(true);
        txtCelular.setEnabled(true);
        txtCorreo.setEnabled(true);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }// fin del método habilitar

    /**
     * Méotodo para validar que todos los campos esten llenos
     * @return true si todo está correcto, false si faltan datos
     */
    private boolean validar() {
        boolean validacion = false;
        
        if(nombre.equals("")){
            JOptionPane.showMessageDialog(null, "<html><h2>LLena el campo Nombre</h2></html>");
            txtNombre.requestFocusInWindow();
            return validacion;
        }// fin del if Nombre
        
         if(paterno.equals("")){
            JOptionPane.showMessageDialog(null, "<html><h2>LLena el campo Apellido Paterno</h2></html>");
            txtPaterno.requestFocusInWindow();
            return validacion;
        }// fin del if Paterno
         
          if(materno.equals("")){
            JOptionPane.showMessageDialog(null, "<html><h2>LLena el campo Apellido Materno</h2></html>");
            txtMaterno.requestFocusInWindow();
            return validacion;
        }// fin del if Materno
          
        if(domicilio.equals("")){
            JOptionPane.showMessageDialog(null, "<html><h2>LLena el campo Domicilio</h2></html>");
            txtDomicilio.requestFocusInWindow();
            return validacion;
        }//fin dle if Domicilio
        
        if(celular.equals("")){
            JOptionPane.showMessageDialog(null, "<html><h2>LLena el campo Celular</h2></html>");
            txtCelular.requestFocusInWindow();
            return validacion;
        }//fin del if Celular
        
        if(correo.equals("")){
            JOptionPane.showMessageDialog(null, "<html><h2>LLena el campo Correo</h2></html>");
            txtCorreo.requestFocusInWindow();
            return validacion;
        }// fin del if Correo
        
        return true;
    }// fin del método validar

    /**
     * Metodo para Mandar Mensaje de Error
     * @param ex 
     */
    private void mensajeError(DAOException ex) {
        //Si getMessage existe obtenemos su valor
        String mensajeError;

        try{
            mensajeError = "Mensaje: " + ex.getCause().getMessage();
        }catch(NullPointerException error){
            mensajeError = "";
        }// fin del catch

        JOptionPane.showMessageDialog(null, ex.getMessage()+"\n"+mensajeError,"ERROR",
                JOptionPane.ERROR_MESSAGE);
    }// fin del método mensajeError

    /**
     * Método para limpiar las cajas de texto
     */
    private void limpiarFormulario() {
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtDomicilio.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
    }// fin del método limpiarFormulario

}// fin de la clase JDGesEditarCli
